export const SWITCH_LOGIN_MODAL = 'SWITCH_LOGIN_MODAL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SHOW_LOGIN_ERROR = 'SHOW_LOGIN_ERROR';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';

export const SWITCH_CREATE_TODO_MODAL = 'SWITCH_CREATE_TODO_MODAL';
export const SWITCH_UPDATE_TODO_MODAL = 'SWITCH_UPDATE_TODO_MODAL';
export const EDIT_TODO = 'EDIT_TODO';
export const CHECK_TODO = 'CHECK_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const RENDER_TODOS = 'RENDER_TODOS';
export const UPDATE_TODO_FORM = 'UPDATE_TODO_FORM';
export const SHOW_TODO_FORM_ERRORS = 'SHOW_TODO_FORM_ERRORS';
export const NETWORK_ERROR = 'NETWORK_ERROR';

export const NULL = 'NULL';
